### ISSUE TITLE
Suggestion: Change the name in the godot asset library

### ISSUE THREAD

**Issue by Gnumaru** [QJPG/GodotNode2Tile#1]
Pelos prints na asset library eu suponho que você seja um falante nativo de português (como eu), mas eu vou escrever em inglês em consideração ao restante da internet.

The idea of recreating the workflow of crocotile inside of godot is awesome =). But using "Godot Crocotile 3D | GodotNode2Tile" as the asset library name may make people think this is an import plugin for crocotile files, wich may break users expectations.

You could still make a reference to crocotile while at the same time making it clear this has nothing to do at all with crocotile besides being inspired on it. For example, the name could be "GodotNode2Tile: A 3D quad based tile editor" or you could change the name altogether to something like "Crocodot" or "GodoTile" so you would have "Crocodot: A 3D quad based tile editor" or "Crocodot: A Crocotile-esque 3D quad based tile editor"

**Comment by Farouk-Loubaki** [comment]
I Agree, that exactly what happened to me

**Comment by QJPG** [comment]
It's been a while, since the last commit, that I thought about changing the name of the plugin. Somehow it brought more attention to the project, but it really can be a bit confusing. Thank you for the suggestions.

**Comment by Gnumaru** [comment]
Mentioning Crocotile in the subtitle like in "Crocodot: A Crocotile inspired 3D quad based tile editor" is a way of not confusing the users and, at the same time, taking advantage of search engines when users search for crocotile =)
