### ISSUE TITLE
Put the contents of the GodotNode2Tile folder into an addons folder

### ISSUE THREAD

**Issue by Smorty10** [QJPG/GodotNode2Tile#2]
By moving the addon folder into... well into an addons folder, the user doesn't have to restructure their folder structure before actually using the plugin. It makes usage a lot easier for everyone and keeps newcomers from becoming confused why your cool plugin doesn't show up in the project settings.

**Comment by QJPG** [comment]
Fixed in the last commit. Thanks for the feedback!!👍
