### ISSUE TITLE
Please add some kind of instructions

### ISSUE THREAD

**Issue by Smorty10** [QJPG/GodotNode2Tile#3]
Currently it is very difficult to pin down exactly what your plugin does. One seems to be able to edit vertecies, but on what is not clear. On a MeshInstance perhaps? Or maybe it has its own mesh generator which then feeds the vetex positions to a shader? An instruction video or some simple documentation on how to use the plugin would be appreciated very much.

**Comment by QJPG** [comment]
It's a great idea! I made a short video demonstrating the basic use of the plugin. Thanks for the feedback 👍
